#!/bin/sh

# if iptables -t filter -C INPUT -m set --match-set ad dst -j REJECT 2>/dev/null; then
#     echo ad rule already added
# else
#     iptables -t filter -A INPUT -m set --match-set ad dst -j REJECT
#     echo added ad rule
# fi

if iptables -t nat -C PREROUTING -p tcp -m set --match-set gw dst -j REDIRECT --to-port 1080 2>/dev/null; then
  echo gw rule already added
else
  # restore ipset
  ipset-restore
  iptables -t nat -A PREROUTING -p tcp -m set --match-set gw dst -j REDIRECT --to-port 1080
  iptables -t nat -A PREROUTING -p udp -m set --match-set gw dst -j REDIRECT --to-port 1080
  echo added gw rule
fi
