#!/bin/sh

# primary wan and connected
if [[ $1==0 && $2==connected ]]; then
  cru a apply-iptables "*/3 * * * *" "apply-iptables" # every 3min
  cru a ipset-save "*/3 * * * *" "ipset-save"
  cru a start-trojan "*/10 * * * *" "start-trojan" # every 10min
  cru a restart-trojan "0 * * * *" "restart-trojan"  # every 1 hour
fi
