#!/bin/sh

config_home=/jffs/configs/v2ray

if iptables -t filter -C INPUT -m set --match-set ad dst -j REJECT 2>/dev/null; then
    echo ad rule already added
else
    ipset -R <$config_home/ad.ips
    iptables -t filter -A INPUT -m set --match-set ad dst -j REJECT
    echo added ad rule
fi

if iptables -t nat -C PREROUTING -p tcp -m set --match-set gw dst -j REDIRECT --to-port 1081 2>/dev/null; then
    echo gw rule already added
else
    ipset -R <$config_home/gw.ips
    iptables -t nat -A PREROUTING -p tcp -m set --match-set gw dst -j REDIRECT --to-port 1081
    echo added gw rule
fi
