#!/bin/bash

set -e

ssh_server=${ssh_server:-192.168.1.1}

v2ray_version=4.33.0
arch=linux-arm32-v5
config_home=${router_config_dir:-/jffs/configs/v2ray}
router_v2ray_config_path=$config_home/$(basename $v2ray_config)

#
# ─── V2RAY ──────────────────────────────────────────────────────────────────────
#

# download, extract and upload v2ray
v2ray_zip=v2ray-${arch}.zip
if [[ ! -e $v2ray_zip ]]; then
  curl -LO https://github.com/v2fly/v2ray-core/releases/download/v${v2ray_version}/${v2ray_zip}
  unzip v2ray-${arch}.zip -d v2ray-${arch}
fi
rsync -av v2ray-$arch/v2* $ssh_server:/opt/bin/

# upload client config
rsync -av $v2ray_config $ssh_server:$router_v2ray_config_path

# start v2ray after every reboot
sed -i.bak "s|^\(CONFIG_PATH=\).*|\1$router_v2ray_config_path|" S22v2ray
rsync -av S22v2ray $ssh_server:/opt/etc/init.d/S22v2ray

# start v2ray now
ssh $ssh_server "/opt/etc/init.d/S22v2ray start"
# ────────────────────────────────────────────────────────────────────────────────

#
# ─── DNSMASQ ────────────────────────────────────────────────────────────────────
#

# upload configs
rsync -av configs/ $ssh_server:$config_home/

# add apply_iptables command and run once
# apply_tables would create ipsets
sed -i.bak "s|^\(config_home=\).*|\1$config_home|" apply_iptables
rsync -av apply_iptables $ssh_server:/opt/bin/apply_iptables
ssh $ssh_server "apply_iptables"

# let dnsmasq use custom dnsmasq config
# 解析国外域名并保存到 ipset 中
ssh $ssh_server "echo \"conf-dir=$config_home, *.hosts\" > /jffs/configs/dnsmasq.conf.add"

# 重启 dnsmasq
ssh $ssh_server "service dnsmasq_restart"
# ────────────────────────────────────────────────────────────────────────────────

#
# ─── JFFS ───────────────────────────────────────────────────────────────────────
#

rsync -av jffs/ $ssh_server:/jffs/scripts/

# start the cru job
ssh $ssh_server "/jffs/scripts/wan-event 1 connected"
# ────────────────────────────────────────────────────────────────────────────────
