#!/bin/sh

CONFIG_PATH=/jffs/configs/v2ray/private_v2ray_client.json
ENABLED=yes
PROCS=v2ray
ARGS="-config $CONFIG_PATH"
PREARGS=""
DESC=$PROCS
PATH=/opt/sbin:/opt/bin:/opt/usr/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

[ -z "$(which $PROCS)" ] && exit 0

. /opt/etc/init.d/rc.func
